title: <img src="https://media.discordapp.net/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png" alt="Gas Brake Go">  
markdown: kramdown
google_analytics: G-SFJ80L12D6
theme: minima
